# Generated by Django 4.1.3 on 2022-12-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mas_vistas', models.CharField(max_length=40)),
                ('taquilla', models.IntegerField()),
                ('critica_peliculas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mas_vistas', models.CharField(max_length=40)),
                ('taquilla', models.IntegerField()),
                ('critica_peliculas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Terror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mas_vistas', models.CharField(max_length=40)),
                ('taquilla', models.IntegerField()),
                ('critica_peliculas', models.CharField(max_length=40)),
            ],
        ),
    ]
